apiVersion: v1
kind: Secret
metadata:
  name: social-media-secrets
  namespace: social-media
type: Opaque
data:
  # Base64 encoded values
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cG9zdGdyZXM=  # postgres
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # your-super-secret-jwt-key-change-this-in-production
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==  # minioadmin
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==  # minioadmin