groups:
  - name: social_media_alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name=~"social-media-.*"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.name }}"
          description: "CPU usage is {{ $value }}% on container {{ $labels.name }}"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{name=~"social-media-.*"} / container_spec_memory_limit_bytes{name=~"social-media-.*"} > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage on {{ $labels.name }}"
          description: "Memory usage is {{ $value | humanizePercentage }} on container {{ $labels.name }}"

      - alert: DatabaseConnectionsHigh
        expr: db_connections_active > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database has {{ $value }} active connections"

      - alert: RedisConnectionsHigh
        expr: redis_connections_active > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Redis connections"
          description: "Redis has {{ $value }} active connections"

      - alert: WebSocketConnectionsHigh
        expr: websocket_connections_active > 1000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High WebSocket connections"
          description: "{{ $value }} active WebSocket connections"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      - alert: DiskSpaceHigh
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.device }}"